### ISSUE TITLE
Toggle comment and toggle comment block are hardcoded

### ISSUE THREAD

**Issue by BeardedBeaver** [cpeditor/QCodeEditor#10]
In a current codebase `toggleComment` and `toggleCommentBlock` methods use hardcoded comment symbols and require `QCodeEditor` widget to have the corresponding highlighter header to be included. This breaks the expandibility of this library.

I suggest to introduce a member for a `QStyleSyntaxHighlighter` class for a single line comment, begind and end of a block comment and use these variables to toggle a comment properly, or skip toggle if current highlighter doesn't have info about comment symbols.

**Comment by coder3101** [comment]
> I suggest to introduce a member for a `QStyleSyntaxHighlighter` class for a single line comment, behind and end of a block comment and use these variables to toggle a comment properly or skip toggle if current highlighter doesn't have info about comment symbols.

Seems a nice idea. Please propose a PR

**Comment by BeardedBeaver** [comment]
I will, thanks

**Comment by BeardedBeaver** [comment]
I have it implemented but I'd prefer to wait until my PR is accelted to have JS comments support as well
