### ISSUE TITLE
Question: Which fork of QCodeEditor shall I use

### ISSUE THREAD

**Issue by FlorianReimold** [cpeditor/QCodeEditor#43]
Hi everybody,

I want to include a Code Editor in my Qt Application (The monitor of [Eclipse eCAL](https://github.com/eclipse-ecal/ecal)) and quickly found the original Megaxela/QCodeEditor repo. As that one seems to be unmaintained, I check the forks and found this repo.

- I currently have the following requirements:
    - Qt 5.9 - 5.15 compatibility (Qt6 is planned for the future
    - Usable on Ubuntu 20.04 and up (x64 and ARM64), as well as Windows 10 (x64)
    - Read-only code display with line numbers and syntax highlighting (Protobuf DebugString syntax, similar to JSON)
    - Word-wrapping
    - Full-text-search for a single document
    - Collapsible code blocks (this is optional an I think that feature is not supported by QCodeEditor)

- Do you think I will be happy with this Widget, or should I use something else?
- Do I assume correctly, that this repo is the version that is actively used in the cpeditor?
- Which version do you suggest me to use? The current master/HEAD?

Kind Regards
Florian Reimold

**Comment by ouuan** [comment]
CP Editor now uses this repo, but CP Editor is not actively maintained.

You can try https://github.com/KDE/syntax-highlighting and refer to its examples.

**Comment by knarfS** [comment]
Hi Florian,

I'm using QCodeEditor (current HEAD) for [SmuView](https://sigrok.org/wiki/SmuView) and at the moment I'm following the cpeditor/QCodeEditor repository, but had my own patches in the past (which are now merged into this repository).
I'm planing to migrate QCodeEditor to Qt6 in the future.

There is also a chain of forks (all based on each other) from Megaxela/QCodeEditor -> [jcelerier/QCodeEditor](https://github.com/jcelerier/QCodeEditor) -> [arucil/QCodeEditor](https://github.com/arucil/QCodeEditor) -> [justxi/QCodeEditor](https://github.com/justxi/QCodeEditor) -> [MathiasPaulin/QCodeEditor](https://github.com/MathiasPaulin/QCodeEditor), making QCodeEditor Qt6 ready, refactoring code, enhancing and fixing bugs. But I haven't looked at these forks in detail yet.

There is no syntax highlighting for Protobuf DebugString in QCodeEditor, so you'll have to add regular expressions for that by yourself.

There is also the Qt (5+6) [QSyntaxHighlighter](https://doc.qt.io/qt-5/qsyntaxhighlighter.html) class, which is also using regular expressions for syntax highlighting. Maybe this is all you need, when you only want a road-only viewer?

For searching you can have a look at [QtFindReplaceDialog](https://github.com/dewhisna/QtFindReplaceDialog) (or [cpeditors fork](https://github.com/cpeditor/QtFindReplaceDialog) or [my fork](https://github.com/knarfS/QtFindReplaceDialog))

Hope that helps,
Frank

**Comment by FlorianReimold** [comment]
Hey, @knarfS and @ouuan,

Thanks for those recommendations! I decided to got with a plain text edit set to read-only mode and a `QSyntaxHighlighter`. This doesn't offer all the feature that QCodeEditor or KSyntaxHighlighter would have, but it is much slimmer, doesn't require an additional dependency and is therefore easier for me to maintain and expand in the future.

Kind regards
Florian
